### ISSUE TITLE
New Control: choice_custom

### ISSUE THREAD

**Issue by ntncmch** [epicentre-msf/outbreak-tools#228]
**Is your feature request related to a problem? Please describe.**
Field wants to add choices manually without having to ask for a new template. 
Ex: multiple site entered in the same linelist (mobile clinics) and new mobile clinics open every week.

**Describe the solution you'd like**

Add control `choice_custom` in the setup. 

The variable is created in the linelist as well as a table object in a new `Custom choices` sheet.

The table has the variable name as header and the user can add choices manually.

The variable in the linelist takes the options among the choices.

It should be possible to re-order the choices in the table object using the excel filter.

When you migrate the data, the Custom choices are also migrated (otherwise they are lost).

**Comment by yves-amevoin** [comment]
I see.  We can implement it at the linelist level pretty easily.
