### ISSUE TITLE
export analyses : avoir un bouton dédié

### ISSUE THREAD

**Issue by MarineDurthaler** [epicentre-msf/outbreak-tools#238]
ne pas intégrer les analyses dans les exports (supprimer la colonne export analysis du set-up), mais ajouter un bouton toujours présent dans export data avec "export analyses", 
on pourrait le faire avec le set-up actuel, en créant un export seulement pour les analyses mais ça prendrait un export tout le temps, donc on n'en aurait plus que 4 vraiment customs.

**Comment by yves-amevoin** [comment]
Merci Marine pour la proposition.

On en a déjà discuté dans #220, où j'ai effectué trois propositions. La proposition du bouton des analyses, correspond à l'option 2 où on exporte toutes les tables vers une feuille unique.

J'ai proposé ces options à @ntncmch, et nous avons retenue l'option 1, qui consiste à mettre la colonne export analysis dans les exports, avec comme proposition que l'on puisse juste faire un export pour les analyses uniquement (comme précisé dans le issue) si l'on veut. L'avantage est qu'on peut inclure aussi dans un export avec des données, des analyses. J'ai réitéré à plusieurs reprises la question afin de m'assurer que l'on opte vraiment pour l'option 1, et d'opter pour son inclusion dans le développement depuis le setup jusqu'au designer. A plusieurs reprises on a choisi cette option. C'est un peu comme s'il faut complètement supprimer le code précédemment écrit et revenir à l'option 2 que j'avais proposée avec toutes les tables exportées.

Ca ne me dérange pas de mettre un bouton pour les exports dans la feuille analyse. Je propose d'ajouter ce bouton sans forcément supprimer la colonne export analyse du setup, pour éviter de revenir complètement derrière sur le travail effectué pendant plusieurs jours pour l'ajout de l'export des analyses, et dans ce cas, on reviendrait à un mixte entre l'option 1 et 2, que j'avais aussi proposé sur #220.
