### ISSUE TITLE
set-up - analyses spatiales : absence de % dans table et graph même quand add percentage = yes

### ISSUE THREAD

**Issue by MarineDurthaler** [epicentre-msf/outbreak-tools#266]
quand on sélectionne add percentage  = yes, pour des analyses spatiales, les % ne sont pas afficher ni dans le graph ni dans la table correspondante : 
- soit afficher les pourcentages
-  soit retirer la colonne
- soit mettre un message d'erreur en attendant que la fonction soit dispo (si on compte la rendre dispo)

**Comment by yves-amevoin** [comment]
This should be fixed
