### ISSUE TITLE
designer : import passwords

### ISSUE THREAD

**Issue by MarineDurthaler** [epicentre-msf/outbreak-tools#268]
créer une ligne pour l'import des mots de passe  - comme pour les autres fichiers geobase, ribbon - qui ne soit pas bloquant si vide

**Comment by yves-amevoin** [comment]
Je vois.

Je pense qu'on avait convenu ensemble, qu'il faut qu'on aie une feuille de mot de passe par défaut dans le designer, et un warning si l'utilisateur décide de générer la linelist avec le mot de passe par défaut (ou oublie de le faire). Actuellement dans le designer, il y a une case dans le ruban (ignore optional warnings) qui lorsqu'elle est cochée ignore ces warnings là, et ne les ignore pas sinon. Dans la version dev, cette case est cochée par défaut, et sera normalement décochée pour la version main.
