### ISSUE TITLE
discrepancy in epiweek between LL and analyses

### ISSUE THREAD

**Issue by MarineDurthaler** [epicentre-msf/outbreak-tools#274]
the start day of week defined in Info is not taken into account for the week number in the analyses so that create discrepancies. 

![image](https://github.com/epicentre-msf/outbreak-tools/assets/74416404/7096f76a-c266-4ef1-a382-93b34cb6ff12)

![image](https://github.com/epicentre-msf/outbreak-tools/assets/74416404/dc06239d-b704-4746-bfbd-84ce975d927a)

email sent with SDN LL .

**Comment by yves-amevoin** [comment]
Fix: Create a form for the selection of start week of all epiweek functions, and add buttons for the selection of the start of the week.
