### ISSUE TITLE
annulation d'un import?

### ISSUE THREAD

**Issue by MarineDurthaler** [epicentre-msf/outbreak-tools#276]
déroulement des actions : 

- import data
- select file
-  "the Workbook contains data, do you want to delete ALL the data before imports? "
       - "Yes"
- enter file name
       -  "Cancel"
**- You entered a bad workbook name. Do you still want to delete before importing data? **  <= _not exactly what you expect after cancelling the action._ 
       -  No
-  the Workbook contains data, do you want to delete ALL the data before imports? 
       -  No
- Finished imports

plus moyen d'annuler la procédure d'import une fois qu'on a sélectionné un fichier?

**Comment by yves-amevoin** [comment]
Le processus est maintenant géré, avec un rappel au début pour l'utilisateur
