### ISSUE TITLE
set-up : error message incoherent

### ISSUE THREAD

**Issue by MarineDurthaler** [epicentre-msf/outbreak-tools#284]
in checks , error message for an export's file name missing whereas it is filled. 

![image](https://github.com/user-attachments/assets/5f420f0b-4047-410c-b96d-f557a5599f2f)
![image](https://github.com/user-attachments/assets/584c143e-8df0-4baa-8e63-0bab940a90ac)
![image](https://github.com/user-attachments/assets/e28670b8-efe4-4095-8617-eaa79ba7aa5e)
![image](https://github.com/user-attachments/assets/fac787d3-9658-4474-9e2b-fee8c6c207ad)

**Comment by yves-amevoin** [comment]
Fixed in the setup, related to the checking informations in the setup formula worksheet.
