### ISSUE TITLE
time series table order 

### ISSUE THREAD

**Issue by MarineDurthaler** [epicentre-msf/outbreak-tools#285]
![image](https://github.com/user-attachments/assets/3eabd052-3ad2-4e87-8a87-14f87f5f11c0)

**Comment by MarineDurthaler** [comment]
idem en numérotant les autres time series

**Comment by MarineDurthaler** [comment]
tjs le problème de menu déroulant même sans table order

**Comment by yves-amevoin** [comment]
Fixed
